server:
  port: ${platform.service.monitor.server.port}
eureka:
  client:
    serviceUrl:
      defaultZone: http://${platform.service.center.server.host}:${platform.service.center.server.port}/eureka/
feign:
  hystrix:
    enabled: true